CLOUDSTACK-81: Fix init script for usage server on RHEL based platforms

diff --git a/usage/distro/centos/SYSCONFDIR/rc.d/init.d/cloud-usage.in b/usage/distro/centos/SYSCONFDIR/rc.d/init.d/cloud-usage.in
--- a/usage/distro/centos/SYSCONFDIR/rc.d/init.d/cloud-usage.in
+++ b/usage/distro/centos/SYSCONFDIR/rc.d/init.d/cloud-usage.in
@@ -30,7 +30,7 @@
 # specific language governing permissions and limitations
 # under the License.
 
-. /lib/lsb/init-functions
+. /etc/rc.d/init.d/functions
 
 SHORTNAME="cloud-usage"
 PIDFILE=@PIDDIR@/"$SHORTNAME".pid
@@ -66,27 +66,26 @@ export CLASSPATH="$SCP:$DCP:$UCP:$JCP:@USAGESYSCONFDIR@"
 
 start() {
     if [ -s "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") >/dev/null 2>&1; then
-        log_daemon_msg "$PROGNAME apparently already running"
-        log_end_msg 0
+        echo "$PROGNAME apparently already running"
         exit 0
     fi
 
-    log_daemon_msg "Starting $PROGNAME" "$SHORTNAME"
     if hostname --fqdn >/dev/null 2>&1 ; then
         true
     else
-        log_failure_msg "The host name does not resolve properly to an IP address. Cannot start $PROGNAME"
-        log_end_msg 1
+        echo "The host name does not resolve properly to an IP address. Cannot start $PROGNAME"
         exit 1
     fi
 
-    if start_daemon -p $PIDFILE $DAEMON -cp "$CLASSPATH" -pidfile "$PIDFILE" -user "$USER" -outfile SYSLOG -errfile SYSLOG -Dpid=$$ $CLASS
+    echo -n "Starting $PROGNAME" "$SHORTNAME"
+
+    if start_daemon -p $PIDFILE $DAEMON -cp "$CLASSPATH" -pidfile "$PIDFILE" -user "$USER" -errfile SYSLOG -Dpid=$$ $CLASS
         RETVAL=$?
     then
         rc=0
         sleep 1
         if ! kill -0 $(cat "$PIDFILE") >/dev/null 2>&1; then
-            log_failure_msg "$PROG failed to start"
+            failure
             rc=1
         fi
     else
@@ -94,18 +93,24 @@ start() {
     fi
 
     if [ $rc -eq 0 ]; then
-        log_end_msg 0
+        success
     else
-        log_end_msg 1
+        failure
         rm -f "$PIDFILE"
     fi
+    echo
 }
 
 stop() {
-    log_daemon_msg "Stopping $PROGNAME" "$SHORTNAME"
+    echo -n "Stopping $PROGNAME" "$SHORTNAME"
     killproc -p $PIDFILE $DAEMON
-    log_end_msg $?
+    if [ "$?" -eq 0 ]; then
+        success
+    else
+        failure
+    fi
     rm -f "$PIDFILE"
+    echo
 }
 
 case "$1" in
@@ -116,7 +121,7 @@ case "$1" in
         stop
         ;;
     status)
-        status_of_proc -p "$PIDFILE" "$PROG" "$SHORTNAME"
+        status -p $PIDFILE $SHORTNAME
         RETVAL=$?
         ;;
     restart | force-reload)
