Refactor cert patching for systemVMs + update keystore-cert-import script + patch-sysvms script + remove patchSysvmCommand from networkelementcommand

diff --git a/scripts/util/keystore-cert-import b/scripts/util/keystore-cert-import
--- a/scripts/util/keystore-cert-import
+++ b/scripts/util/keystore-cert-import
@@ -18,15 +18,14 @@
 
 PROPS_FILE="$1"
 KS_PASS="$2"
-KS_VALIDITY="$3"
-KS_FILE="$4"
-MODE="$5"
-CERT_FILE="$6"
-CERT=$(echo "$7" | tr '^' '\n' | tr '~' ' ')
-CACERT_FILE="$8"
-CACERT=$(echo "$9" | tr '^' '\n' | tr '~' ' ')
-PRIVKEY_FILE="${10}"
-PRIVKEY=$(echo "${11}" | tr '^' '\n' | tr '~' ' ')
+KS_FILE="$3"
+MODE="$4"
+CERT_FILE="$5"
+CERT=$(echo "$6" | tr '^' '\n' | tr '~' ' ')
+CACERT_FILE="$7"
+CACERT=$(echo "$8" | tr '^' '\n' | tr '~' ' ')
+PRIVKEY_FILE="$9"
+PRIVKEY=$(echo "${10}" | tr '^' '\n' | tr '~' ' ')
 
 ALIAS="cloud"
 SYSTEM_FILE="/var/cache/cloud/cmdline"
@@ -44,13 +43,14 @@ if [ ! -f "$LIBVIRTD_FILE" ]; then
       fi
   fi
 
-  if [ -f "$KS_FILE" ]; then
-      keytool -delete -noprompt -alias "$ALIAS" -keystore "$KS_FILE" -storepass "$KS_PASS" > /dev/null 2>&1 || true
-  fi
-
-  CN=$(hostname --fqdn)
-  keytool -genkey -storepass "$KS_PASS" -keypass "$KS_PASS" -alias "$ALIAS" -keyalg RSA -validity "$KS_VALIDITY" -dname cn="$CN",ou="cloudstack",o="cloudstack",c="cloudstack" -keystore "$KS_FILE" > /dev/null 2>&1
+#  if [ -f "$KS_FILE" ]; then
+#      keytool -delete -noprompt -alias "$ALIAS" -keystore "$KS_FILE" -storepass "$KS_PASS" > /dev/null 2>&1 || true
+#  fi
+#
+#  CN=$(hostname --fqdn)
+#  keytool -genkey -storepass "$KS_PASS" -keypass "$KS_PASS" -alias "$ALIAS" -keyalg RSA -validity "$KS_VALIDITY" -dname cn="$CN",ou="cloudstack",o="cloudstack",c="cloudstack" -keystore "$KS_FILE" > /dev/null 2>&1
 fi
+
 # Find keystore password
 KS_PASS=$(sed -n '/keystore.passphrase/p' "$PROPS_FILE" 2>/dev/null  | sed 's/keystore.passphrase=//g' 2>/dev/null)
 
@@ -62,11 +62,17 @@ fi
 # Import certificate
 if [ ! -z "${CERT// }" ]; then
     echo "$CERT" > "$CERT_FILE"
+elif [ ! -f "$CERT_FILE" ]; then
+   echo "Cannot find certificate file: $CERT_FILE, exiting"
+   exit
 fi
 
 # Import ca certs
 if [ ! -z "${CACERT// }" ]; then
     echo "$CACERT" > "$CACERT_FILE"
+elif [ ! -f "$CACERT_FILE" ]; then
+    echo "Cannot find ca certificate file: $CACERT_FILE, exiting!"
+    exit
 fi
 
 # Import cacerts into the keystore
@@ -77,9 +83,16 @@ for caChain in $(ls cloudca.*); do
 done
 rm -f cloudca.*
 
+# Stop cloud service in systemvm
+if [ "$MODE" == "ssh" ] && [ -f $SYSTEM_FILE ]; then
+    systemctl stop cloud > /dev/null 2>&1
+fi
+
 # Import private key if available
 if [ ! -z "${PRIVKEY// }" ]; then
     echo "$PRIVKEY" > "$PRIVKEY_FILE"
+fi
+if [ -f "$PRIVKEY_FILE" ]; then
     # Re-initialize keystore when private key is provided
     keytool -delete -noprompt -alias "$ALIAS" -keystore "$KS_FILE" -storepass "$KS_PASS" 2>/dev/null || true
     openssl pkcs12 -export -name "$ALIAS" -in "$CERT_FILE" -inkey "$PRIVKEY_FILE" -out "$KS_FILE.p12" -password pass:"$KS_PASS" > /dev/null 2>&1
@@ -115,6 +128,10 @@ if [ -f "$SYSTEM_FILE" ]; then
     chmod 644 /usr/local/share/ca-certificates/cloudstack/ca.crt
     update-ca-certificates > /dev/null 2>&1 || true
 
+    # Ensure cloud service is running in systemvm
+    if [ "$MODE" == "ssh" ]; then
+        systemctl start cloud > /dev/null 2>&1
+    fi
 fi
 
 # Fix file permission
