ha, multi-master support
Support for multi-master Kubernetes cluster for Kubernetes version 1.16 and above

Signed-off-by: Abhishek Kumar <abhishek.mrt22@gmail.com>

diff --git a/plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-master.yml b/plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-master.yml
--- a/plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-master.yml
+++ b/plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-master.yml
@@ -33,12 +33,9 @@ write-files:
 
       export PATH=$PATH:/opt/bin
 
-      RELEASE="v1.11.4"
       ISO_MOUNT_DIR=/mnt/k8sdisk
-      BINARIES_DIR=${ISO_MOUNT_DIR}/${RELEASE}
-      CNI_VERSION="v0.7.1"
-      CRICTL_VERSION="v1.11.1"
-      ATTEMPT_OFFLINE_INSTALL=true
+      BINARIES_DIR=${ISO_MOUNT_DIR}/
+      ATTEMPT_ONLINE_INSTALL=false
       setup_complete=false
 
       OFFLINE_INSTALL_ATTEMPT_SLEEP=5
@@ -85,10 +82,10 @@ write-files:
         ### Binaries available offline ###
         echo "Installing binaries from ${BINARIES_DIR}"
         mkdir -p /opt/cni/bin
-        tar -f "${BINARIES_DIR}/cni/${CNI_VERSION}/cni-plugins-amd64-${CNI_VERSION}.tgz" -C /opt/cni/bin -xz
+        tar -f "${BINARIES_DIR}/cni/cni-plugins-amd64.tgz" -C /opt/cni/bin -xz
 
         mkdir -p /opt/bin
-        tar -f "${BINARIES_DIR}/cri-tools/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" -C /opt/bin -xz
+        tar -f "${BINARIES_DIR}/cri-tools/crictl-linux-amd64.tar.gz" -C /opt/bin -xz
 
         mkdir -p /opt/bin
         cd /opt/bin
@@ -123,8 +120,11 @@ write-files:
         fi
         umount "${ISO_MOUNT_DIR}" && rmdir "${ISO_MOUNT_DIR}"
       fi
-      if [ "$setup_complete" = false ]; then
+      if [ "$setup_complete" = false ] && [ "$ATTEMPT_ONLINE_INSTALL" = true ]; then
         ###  Binaries not available offline ###
+        RELEASE="v1.16.3"
+        CNI_VERSION="v0.7.5"
+        CRICTL_VERSION="v1.16.0"
         echo "Warning: ${BINARIES_DIR} not found. Will get binaries and docker images from Internet."
         mkdir -p /opt/cni/bin
         curl -L "https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-amd64-${CNI_VERSION}.tgz" | tar -C /opt/cni/bin -xz
@@ -145,22 +145,25 @@ write-files:
       systemctl enable kubelet && systemctl start kubelet
       modprobe br_netfilter && sysctl net.bridge.bridge-nf-call-iptables=1
 
-      crucial_cmd_attempts=1
-      while true; do
-        if (( "$crucial_cmd_attempts" > "$MAX_SETUP_CRUCIAL_CMD_ATTEMPTS" )); then
-          echo "Error: kubeadm pull images failed!"
-          exit 1
-        fi
-        retval=0
-        set +e
-        kubeadm config images pull
-        retval=$?
-        set -e
-        if [ $retval -eq 0 ]; then
-          break;
-        fi
-        crucial_cmd_attempts=$[$crucial_cmd_attempts + 1]
-      done
+      if [ -d "$BINARIES_DIR" ] && [ "$ATTEMPT_ONLINE_INSTALL" = true ]; then
+        crucial_cmd_attempts=1
+        while true; do
+          if (( "$crucial_cmd_attempts" > "$MAX_SETUP_CRUCIAL_CMD_ATTEMPTS" )); then
+            echo "Warning: kubeadm pull images failed after multiple tries!"
+            break;
+          fi
+          retval=0
+          set +e
+          kubeadm config images pull
+          retval=$?
+          set -e
+          if [ $retval -eq 0 ]; then
+            break;
+          fi
+          crucial_cmd_attempts=$[$crucial_cmd_attempts + 1]
+        done
+      fi
+
       crucial_cmd_attempts=1
       while true; do
         if (( "$crucial_cmd_attempts" > "$MAX_SETUP_CRUCIAL_CMD_ATTEMPTS" )); then
@@ -169,7 +172,7 @@ write-files:
         fi
         retval=0
         set +e
-        kubeadm init --pod-network-cidr=10.244.0.0/16 --token {{ k8s_master.cluster.token }} {{ k8s_master.cluster.ip }}
+        kubeadm init --token {{ k8s_master.cluster.token }} {{ k8s_master.cluster.initargs }}
         retval=$?
         set -e
         if [ $retval -eq 0 ]; then
@@ -183,6 +186,10 @@ write-files:
     owner: root:root
     content: |
       #!/bin/bash -e
+
+      ISO_MOUNT_DIR=/mnt/k8sdisk
+      BINARIES_DIR=${ISO_MOUNT_DIR}/
+
       if [[ $(systemctl is-active setup-kube-system) != "inactive" ]]; then
         echo "setup-kube-system is running!"
         exit 1
@@ -195,12 +202,19 @@ write-files:
       chown $(id -u):$(id -g) /root/.kube/config
       echo export PATH=\$PATH:/opt/bin >> /root/.bashrc
 
-      kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
-      kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.0/src/deploy/recommended/kubernetes-dashboard.yaml
+      if [ -d "$BINARIES_DIR" ]; then
+        ### Network, dashboard configs available offline ###
+        echo "Offline configs are available!"
+        kubectl apply -f ${BINARIES_DIR}/network.yaml
+        kubectl apply -f ${BINARIES_DIR}/dashborad.yaml
+      else
+        kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
+        kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta6/aio/deploy/recommended.yaml
+      fi
 
       kubectl create rolebinding admin-binding --role=admin --user=admin || true
       kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=admin || true
-      kubectl create clusterrolebinding kubernetes-dashboard --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard || true
+      kubectl create clusterrolebinding kubernetes-dashboard-ui --clusterrole=cluster-admin --serviceaccount=kubernetes-dashboard:kubernetes-dashboard || true
 
 coreos:
   units:
