Revert "cks: Fix when deployed on a nw without internet access"
This reverts commit 40e3338001b2f1c239533bedac5b60d8b9d2f631.

diff --git a/plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node.yml b/plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node.yml
--- a/plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node.yml
+++ b/plugins/integrations/kubernetes-service/src/main/resources/conf/k8s-control-node.yml
@@ -25,6 +25,26 @@ users:
       {{ k8s.ssh.pub.key }}
 
 write_files:
+  - path: /etc/conf.d/nfs
+    permissions: '0644'
+    content: |
+      OPTS_RPC_MOUNTD=""
+
+  - path: /etc/kubernetes/pki/cloudstack/ca.crt
+    permissions: '0644'
+    content: |
+      {{ k8s_control_node.ca.crt }}
+
+  - path: /etc/kubernetes/pki/cloudstack/apiserver.crt
+    permissions: '0644'
+    content: |
+      {{ k8s_control_node.apiserver.crt }}
+
+  - path: /etc/kubernetes/pki/cloudstack/apiserver.key
+    permissions: '0600'
+    content: |
+      {{ k8s_control_node.apiserver.key }}
+
   - path: /opt/bin/setup-kube-system
     permissions: '0700'
     owner: root:root
@@ -42,8 +62,8 @@ write_files:
       ATTEMPT_ONLINE_INSTALL=false
       setup_complete=false
 
-      OFFLINE_INSTALL_ATTEMPT_SLEEP=30
-      MAX_OFFLINE_INSTALL_ATTEMPTS=40
+      OFFLINE_INSTALL_ATTEMPT_SLEEP=15
+      MAX_OFFLINE_INSTALL_ATTEMPTS=100
       offline_attempts=1
       MAX_SETUP_CRUCIAL_CMD_ATTEMPTS=3
       EJECT_ISO_FROM_OS={{ k8s.eject.iso }}
@@ -131,6 +151,8 @@ write_files:
           done <<< "$output"
           setup_complete=true
         fi
+        mkdir -p "${K8S_CONFIG_SCRIPTS_COPY_DIR}"
+        cp ${BINARIES_DIR}/*.yaml "${K8S_CONFIG_SCRIPTS_COPY_DIR}"
         if [ -e "${BINARIES_DIR}/autoscaler.yaml" ]; then
           mkdir -p /opt/autoscaler
           cp "${BINARIES_DIR}/autoscaler.yaml" /opt/autoscaler/autoscaler_tmpl.yaml
@@ -188,6 +210,23 @@ write_files:
         done
       fi
 
+      crucial_cmd_attempts=1
+      while true; do
+        if (( "$crucial_cmd_attempts" > "$MAX_SETUP_CRUCIAL_CMD_ATTEMPTS" )); then
+          echo "Error: kubeadm init failed!"
+          exit 1
+        fi
+        retval=0
+        set +e
+        kubeadm init --token {{ k8s_control_node.cluster.token }} --token-ttl 0 {{ k8s_control_node.cluster.initargs }} --cri-socket /run/containerd/containerd.sock
+        retval=$?
+        set -e
+        if [ $retval -eq 0 ]; then
+          break;
+        fi
+        crucial_cmd_attempts=$[$crucial_cmd_attempts + 1]
+      done
+
   - path: /opt/bin/deploy-kube-system
     permissions: '0700'
     owner: root:root
@@ -199,18 +238,36 @@ write_files:
       exit 0
       fi
 
+      K8S_CONFIG_SCRIPTS_COPY_DIR=/tmp/k8sconfigscripts/
+
       if [[ $(systemctl is-active setup-kube-system) != "inactive" ]]; then
         echo "setup-kube-system is running!"
         exit 1
       fi
-      modprobe ip_vs
-      modprobe ip_vs_wrr
-      modprobe ip_vs_sh
-      modprobe nf_conntrack
       if [[ "$PATH" != *:/opt/bin && "$PATH" != *:/opt/bin:* ]]; then
         export PATH=$PATH:/opt/bin
       fi
-      kubeadm join {{ k8s_control_node.join_ip }}:6443 --token {{ k8s_control_node.cluster.token }} --discovery-token-unsafe-skip-ca-verification
+      export KUBECONFIG=/etc/kubernetes/admin.conf
+
+      mkdir -p /root/.kube
+      cp -i /etc/kubernetes/admin.conf /root/.kube/config
+      chown $(id -u):$(id -g) /root/.kube/config
+      echo export PATH=\$PATH:/opt/bin >> /root/.bashrc
+
+      if [ -d "$K8S_CONFIG_SCRIPTS_COPY_DIR" ]; then
+        ### Network, dashboard configs available offline ###
+        echo "Offline configs are available!"
+        /opt/bin/kubectl apply -f ${K8S_CONFIG_SCRIPTS_COPY_DIR}/network.yaml
+        /opt/bin/kubectl apply -f ${K8S_CONFIG_SCRIPTS_COPY_DIR}/dashboard.yaml
+        rm -rf "${K8S_CONFIG_SCRIPTS_COPY_DIR}"
+      else
+        /opt/bin/kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(/opt/bin/kubectl version | base64 | tr -d '\n')"
+        /opt/bin/kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta6/aio/deploy/recommended.yaml
+      fi
+
+      /opt/bin/kubectl create rolebinding admin-binding --role=admin --user=admin || true
+      /opt/bin/kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=admin || true
+      /opt/bin/kubectl create clusterrolebinding kubernetes-dashboard-ui --clusterrole=cluster-admin --serviceaccount=kubernetes-dashboard:kubernetes-dashboard || true
 
       sudo touch /home/cloud/success
       echo "true" > /home/cloud/success
@@ -256,7 +313,7 @@ write_files:
       Type=simple
       StartLimitInterval=0
       Restart=on-failure
-      ExecStartPre=/usr/bin/curl -k https://{{ k8s_control_node.join_ip }}:6443/version
+      ExecStartPre=/usr/bin/curl -k https://127.0.0.1:6443/version
       ExecStart=/opt/bin/deploy-kube-system
 
 runcmd:
@@ -269,3 +326,4 @@ runcmd:
   - until [ -f /etc/systemd/system/setup-kube-system.service ]; do sleep 5; done
   - [ systemctl, start, setup-kube-system ]
   - [ systemctl, start, deploy-kube-system ]
+
