Both scripts should be able to use the data-server introduced in 4.4

diff --git a/setup/bindir/cloud-set-guest-sshkey.in b/setup/bindir/cloud-set-guest-sshkey.in
--- a/setup/bindir/cloud-set-guest-sshkey.in
+++ b/setup/bindir/cloud-set-guest-sshkey.in
@@ -37,32 +37,24 @@ for DHCP_FILE in $DHCP_FOLDERS; do
         SSHKEY_SERVER_IP=$(grep dhcp-server-identifier $DHCP_FILE | tail -1 | awk '{print $NF}' | tr -d '\;')
 
         if [ -n "$SSHKEY_SERVER_IP" ]; then
-            logger -t "cloud" "Sending request to ssh key server at $SSHKEY_SERVER_IP"
-
-            publickey=$(wget -q -t 3 -T 20 -O - http://$SSHKEY_SERVER_IP/latest/public-keys)
-
-            if [ $? -eq 0 ]; then
-                logger -t "cloud" "Got response from server at $SSHKEY_SERVER_IP"
-                keys_received=1
-                break
-            fi
+            logger -t "cloud" "Found ssh key server at $SSHKEY_SERVER_IP"
+            break
         else
-            logger -t "cloud" "Could not find ssh key server IP in $DHCP_FILE trying with the name data-server "
+            logger -t "cloud" "Could not find ssh key server IP in $DHCP_FILE"
         fi
     fi
 done
 
-if [ "$keys_received" == "0" ]; then
-    SSHKEY_SERVER_IP=$(nslookup data-server | grep Address |tr '\n' ' '|  awk '{print $4}')
-    logger -t "cloud" "Sending request to ssh key server at $SSHKEY_SERVER_IP"
-     publickey=$(wget -q -t 3 -T 20 -O - http://data-server/latest/public-keys)
-     if [ $? -eq 0 ]
-     then
-        logger -t "cloud" "Got response from server at $SSHKEY_SERVER_IP"
-        keys_received=1
-     else
-        logger -t "cloud" "Could not resolve the name data-server"
-     fi
+if [ -z "$SSHKEY_SERVER_IP" ]; then
+     logger -t "cloud" "Unable to determine the password server, falling back to data-server"
+     SSHKEY_SERVER_IP=data-server
+fi
+ 
+logger -t "cloud" "Sending request to ssh key server at $SSHKEY_SERVER_IP"
+publickey=$(wget -q -t 3 -T 20 -O - http://$SSHKEY_SERVER_IP/latest/public-keys)
+if [ $? -eq 0 ]; then
+    logger -t "cloud" "Got response from server at $SSHKEY_SERVER_IP"
+    keys_received=1
 fi
 
 if [ "$keys_received" == "0" ]; then
