Cloudstack-2644 [Multiple_IP_Ranges] user data service on VR does not work in case of multiple subnets Cloudstack-2953 [Multiple_IP_Ranges] VM does not get the public key from VR incase of multiple subnets per vlan Also removed some unused code and fixed the an error in the dnsmasq config function
Signed-off-by: Abhinandan Prateek <aprateek@apache.org>

diff --git a/setup/bindir/cloud-set-guest-sshkey.in b/setup/bindir/cloud-set-guest-sshkey.in
--- a/setup/bindir/cloud-set-guest-sshkey.in
+++ b/setup/bindir/cloud-set-guest-sshkey.in
@@ -26,37 +26,18 @@
 # Modify this line to specify the user (default is root)
 user=root
 
+SSHKEY_SERVER_IP=$(nslookup data-server | grep Server | awk '{print $2}')
+logger -t "cloud" "Sending request to ssh key server at $SSHKEY_SERVER_IP"
 
+publickey=$(wget -t 3 -T 20 -O - http://data-server/latest/public-keys 2>/dev/null)
 
-# Add your DHCP lease folders here
-DHCP_FOLDERS="/var/lib/dhclient/* /var/lib/dhcp3/*"
-keys_received=0
-file_count=0
-
-for DHCP_FILE in $DHCP_FOLDERS
-do
-	if [ -f $DHCP_FILE ]
-	then
-		file_count=$((file_count+1))
-		SSHKEY_SERVER_IP=$(grep dhcp-server-identifier $DHCP_FILE | tail -1 | awk '{print $NF}' | tr -d '\;')
-
-		if [ -n "$SSHKEY_SERVER_IP" ]
-		then
-			logger -t "cloud" "Sending request to ssh key server at $SSHKEY_SERVER_IP"
-
-			publickey=$(wget -t 3 -T 20 -O - http://$SSHKEY_SERVER_IP/latest/public-keys 2>/dev/null)
-
-			if [ $? -eq 0 ]
-			then
-				logger -t "cloud" "Got response from server at $SSHKEY_SERVER_IP"
-				keys_received=1
-				break
-			fi
-		else
-			logger -t "cloud" "Could not find ssh key server IP in $DHCP_FILE"
-		fi
-	fi
-done
+if [ $? -eq 0 ]
+then
+     logger -t "cloud" "Got response from server at $SSHKEY_SERVER_IP"
+     keys_received=1
+else
+     logger -t "cloud" "Could not find ssh key server IP in $DHCP_FILE"
+fi
 
 # did we find the keys anywhere?
 if [ "$keys_received" == "0" ]
