filesystem and hypervisor specific fsvm init

diff --git a/plugins/storage/fileshare/storagefsvm/src/main/resources/conf/fsvm-init.yml b/plugins/storage/fileshare/storagefsvm/src/main/resources/conf/fsvm-init.yml
--- a/plugins/storage/fileshare/storagefsvm/src/main/resources/conf/fsvm-init.yml
+++ b/plugins/storage/fileshare/storagefsvm/src/main/resources/conf/fsvm-init.yml
@@ -40,9 +40,17 @@ write_files:
 
       sudo mkdir -p "$MOUNT_POINT"
 
-      sudo mkfs.xfs "$PARTITION"
-
-      log "Formatted Partition $PARTITION with XFS Filesystem."
+      FILESYSTEM={{ fsvm.filesystem }}
+      if [ "$FILESYSTEM" == "xfs" ]; then
+        sudo mkfs.xfs "$PARTITION"
+        log "Formatted Partition $PARTITION with XFS Filesystem."
+      elif [ "$FILESYSTEM" == "ext4" ]; then
+        sudo mkfs.ext4 "$PARTITION"
+        log "Formatted Partition $PARTITION with EXT4 Filesystem."
+      else
+        log "Invalid filesystem type specified. Use 'xfs' or 'ext4'."
+        exit 1
+      fi
 
       FS_INFO=$(sudo blkid "$PARTITION")
       UUID=$(echo "$FS_INFO" | grep -oP "UUID=\"\K[^\"]+")
@@ -98,7 +106,17 @@ write_files:
       }
       log "Running resize script."
       PARTITION="$1"
-      sudo xfs_growfs "$PARTITION"
+      
+      FILESYSTEM={{ fsvm.filesystem }}
+      if [ "$FILESYSTEM" == "xfs" ]; then
+        sudo xfs_growfs "$PARTITION"
+      elif [ "$FILESYSTEM" == "ext4" ]; then
+        sudo resize2fs "$PARTITION"
+      else
+        log "Invalid filesystem type specified. Use 'xfs' or 'ext4'."
+        exit 1
+      fi
+      
       log "Finished running resize script."
 
   - path: /usr/local/bin/fsvm-setup
@@ -112,7 +130,29 @@ write_files:
         echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> $LOG_FILE
       }
 
-      BLOCK_DEVICE="vdb"
+      VM_HOSTNAME=$(hostname)
+      VM_IP="127.0.0.1"
+      HOSTS_ENTRY="$VM_IP     $VM_HOSTNAME"
+      if grep -q "$VM_HOSTNAME" /etc/hosts; then
+        log "Hostname entry already exists in /etc/hosts"
+      else
+        # Append the hostname to /etc/hosts
+        echo "$HOSTS_ENTRY" | sudo tee -a /etc/hosts > /dev/null
+        log "Added hostname entry to /etc/hosts: $HOSTS_ENTRY"
+      fi
+      
+      HYPERVISOR_INFO=$(dmesg | grep -i hypervisor)
+      if echo "$HYPERVISOR_INFO" | grep -i "kvm"; then
+        BLOCK_DEVICE="vdb"
+      elif echo "$HYPERVISOR_INFO" | grep -i "xen"; then
+        BLOCK_DEVICE="xvdb"
+      elif echo "$HYPERVISOR_INFO" | grep -i "vmware"; then
+        BLOCK_DEVICE="sdb"
+      else
+        log "Unknown hypervisor"
+        exit 1
+      fi
+      
       PARTITION="/dev/$BLOCK_DEVICE"
       ADD_PARTITION_FILE="/usr/local/bin/add-partition"
       RESIZE_PARTITION_FILE="/usr/local/bin/resize-partition"
