ci test
Signed-off-by: Rohit Yadav <rohit.yadav@shapeblue.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,17 +40,37 @@ jobs:
           python-version: '3.9'
           architecture: 'x64'
 
-      - name: Install dependencies
-        run: |
-          python3 -m pip install --user --upgrade urllib3 lxml paramiko nose texttable ipmisim pyopenssl pycrypto mock flask netaddr pylint pycodestyle six astroid
-          python3 -m pip install --user --upgrade http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.0.4.zip#md5=3df394d89300db95163f17c843ef49df 2>&1 > /dev/null
-
       - name: Install Build Dependencies
         run: |
-          export DEBIAN_FRONTEND=noninteractive
           curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
           sudo apt-get update
-          sudo apt-get install -y git uuid-runtime genisoimage netcat nodejs ipmitool build-essential
+          sudo apt-get install -y git uuid-runtime genisoimage netcat nodejs ipmitool build-essential libgcrypt20 libgpg-error-dev libgpg-error0 libopenipmi0 ipmitool libpython3-dev libssl-dev libffi-dev python3-openssl python3-dev python3-setuptools
+
+      - name: Install Python dependencies
+        run: |
+          python3 -m pip install --user --upgrade urllib3 lxml paramiko nose texttable ipmisim pyopenssl pycrypto mock flask netaddr pylint pycodestyle six astroid
+
+      - name: Install MySQL Server
+        run: |
+          export DEBIAN_FRONTEND=noninteractive
+          sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password password'
+          sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password password'
+          sudo apt-get install -y mysql-server
+          sudo systemctl restart mysql-server
+          sudo mysql -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY ''; FLUSH PRIVILEGES;"
+
+      - name: Env details
+        run: |
+          uname -a
+          whoami
+          javac -version
+          mvn -v
+          python3 --version
+          free -m
+          nproc
+          git status
+          ipmitool -V
+          npm version
 
       - name: Install Noredist Dependencies
         run: |
@@ -60,17 +80,41 @@ jobs:
       #- name: RAT licence checks
       #  run: |
       #    mvn -P developer,systemvm -Dsimulator -Dnoredist -pl . org.apache.rat:apache-rat-plugin:0.12:check
+      #    find rat.txt -type f -exec echo -e "Printing RAT license-failures {} :\n" \; -exec cat {} \;
 
       - name: Build with Maven
         run: |
-          mvn -B -T2 -P developer,systemvm -Dsimulator -Dnoredist clean install
+          mvn -B -T4 -P developer,systemvm -Dsimulator -Dnoredist clean install
 
-      - name: Install Simulator Dependencies
+      - name: Setup Simulator Prerequisites
         run: |
-          export DEBIAN_FRONTEND=noninteractive
-          sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password password'
-          sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password password'
-          sudo apt-get install -y mysql-server
-          mysql -uroot -ppassword -e "SET PASSWORD = PASSWORD(''); FLUSH PRIVILEGES;"
-          sudo systemctl restart mysql-server
+          python3 -m pip install --user --upgrade http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.0.4.zip#md5=3df394d89300db95163f17c843ef49df 2>&1 > /dev/null
+          python3 -m pip install --user --upgrade tools/marvin/dist/Marvin-*.tar.gz
+          mvn -q -Pdeveloper -pl developer -Ddeploydb
+          mvn -q -Pdeveloper -pl developer -Ddeploydb-simulator
+
+      - name: Start CloudStack Management Server with Simulator
+        run: |
+          export MAVEN_OPTS="-Xmx4096m -XX:MaxPermSize=800m -Djava.security.egd=file:/dev/urandom"
+          mvn -Dsimulator -Dorg.eclipse.jetty.annotations.maxWait=120 -pl :cloud-client-ui jetty:run 2>&1 > /tmp/jetty-log &
+          while ! nc -vzw 5 localhost 8096 2>&1 > /dev/null; do grep Exception /tmp/jetty-log; sleep 10; done
+          python3 tools/marvin/marvin/deployDataCenter.py -i setup/dev/advanced.cfg 2>&1 || true
+
+      - name: Run Integration Tests with Simulator
+        run: |
+          mkdir -p integration-test-results/smoke/misc
+          mkdir -p integration-test-results/component
+
+          set -e
+          for suite in "smoke/test_certauthority_root" ; do
+            echo "Currently running test: $suite"
+            time nosetests-3.4 --with-xunit --xunit-file=integration-test-results/$suite.xml --with-marvin --marvin-config=setup/dev/advanced.cfg test/integration/$suite.py -s -a tags=advanced,required_hardware=false --zone=Sandbox-simulator --hypervisor=simulator || true ;
+          done
+
+          find /tmp//MarvinLogs -type f -exec echo -e "Printing marvin logs {} :\n" \; -exec cat {} \;
+
+      - name: Run Integration Tests with Simulator
+        run: |
+          python3 ./tools/travis/xunit-reader.py integration-test-results/
+          mvn -Dsimulator -pl client jetty:stop 2>&1
 
